### ISSUE TITLE
Possible infinite wait

### ISSUE THREAD

**Issue by milesich** [sabloger/sitemap-generator#10]
In `*SitemapIndex.saveSitemaps` and `*SitemapIndex.PingSearchEngines` the `WaitGroup.Done` may never be called when the go routine returns early in case of error and that would cause `WaitGroup.Wait` never stop waiting. To fix it move`s.wg.Done()` to  the top of the go routine using `defer`.  `defer s.wg.Done()`

**Comment by sabloger** [comment]
Done
