### ISSUE TITLE
Trailing slash "/" always been trimmed

### ISSUE THREAD

**Issue by YamiOdymel** [sabloger/sitemap-generator#11]
`sabloger/sitemap-generator` always trims the trailing slash.

```go
sitemap.Add(&smg.SitemapLoc{
	Loc: "about/",
})
```

The code above generates

```xml
<url>
  <loc>https://example.com/about</loc>
</url>
```

Which should be `https://example.com/about/` instead. 

A given result like is making bad Google SEO, because the sitemap is giving URLs that redirecting pages.

**Comment by YamiOdymel** [comment]
I found out that `path.Join` trims it.

https://github.com/sabloger/sitemap-generator/blob/2bf50afb94861abdb73646d339ec2fdd9eb5f036/smg/sitemap.go#L101

Based on the stackoverflow [comment](https://stackoverflow.com/questions/34668012/combine-url-paths-with-path-join#comment129303333_34668130):

> beware that **`path.Join` strips all trailing slashes** (since **it calls `path.Clean`** on the result before returning it) which can break URLs where trailing slashes have importance (a URL path does not necessarily have any relationship to a filesystem path, and so a trailing slash can affect how a URL is interpreted) -- the Go 1.19 solution explicitly addresses this and preserves a single trailing slash

&nbsp;

### Solution 

Based on [stackoverflow answer](https://stackoverflow.com/a/43415988/5203951) that recommends `url.ResolveReference`:

Find the code in `smg/sitemap.go`

```go
output, err := url.Parse(s.Hostname)
if err != nil {
	return err
}
output.Path = path.Join(output.Path, u.Loc)
u.Loc = output.String()
```

Replace with

```go
output, err := url.Parse(s.Hostname)
if err != nil {
	return err
}
loc, err := url.Parse(u.Loc)
if err != nil {
	return err
}
u.Loc = output.ResolveReference(loc).String()
```

It works for me, not sure if it breaks any other stuff.

**Comment by sabloger** [comment]
Hi @YamiOdymel, 
I will check if it's feasible to use. 
Thank you

**Comment by sabloger** [comment]
Fixed
