### ISSUE TITLE
get sitemap.content

### ISSUE THREAD

**Issue by RoomflowTechnik** [sabloger/sitemap-generator#6]
hi,

nice package. thank you.
i am looking for a way to receive the sitmap-content. for example to return it with http.ResponseWriter.Write(content)
think it woul be possible if the there would be a method to get the value from Sitemap.content or if Sitemap.content would be available outside by changing it to Sitemap.Content

do you think this is a good idea?

thank you advance.
best florian

**Comment by sabloger** [comment]
Hi,

I added a Sitemap.WriteTo(io.Writer) method which writes the sitemap content (not for sitemap_index yet).

Use it like this:
```go
// Finalize must be called to make the content closed.
sm.Finalize()

// Needs an io.Writer interface
buf := bytes.Buffer{}
n, err = sm.WriteTo(&buf)
```
